# Generated by Django 4.2.1 on 2023-05-17 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('categoria', models.CharField(choices=[('Cereales', 'Cereales'), ('Frutas', 'Frutas'), ('Verduras', 'Verduras'), ('Legumbres', 'Legumbres'), ('Hortalizas', 'Hortalizas'), ('Bebidas', 'Bebidas')], max_length=50)),
                ('stock', models.IntegerField()),
                ('unidad', models.CharField(choices=[('Unidad', 'Unidad'), ('Decena', 'Decena'), ('Caja', 'Caja')], max_length=50)),
                ('medida', models.CharField(choices=[('Kg', 'Kg'), ('Litro', 'Litro')], max_length=50)),
            ],
        ),
    ]
