# Generated by Django 4.2.1 on 2023-05-17 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='medida',
            field=models.CharField(choices=[('Gramos', 'Gramos'), ('Kg', 'Kg'), ('Litro', 'Litro')], max_length=50),
        ),
    ]
